# Docker compose to build and run the read service
version: '2'
services:
  read-service:
    build:
      context: .
      dockerfile: Dockerfile.configserver
    ports: 
      - "8888:8888"
    network_mode: host