# CloudConfigServer
Spring Cloud Config Server

Spring Cloud Config provides server and client-side support for externalized configuration in a distributed system. 

== Quick Start

Build the server:

----
$ git clone https://github.com/sasikumar-sugumar/CloudConfigServer.git
$ mvn clean install
----

Build and run the container
----
$ docker-compose up -d
----

----
$ curl localhost:8888/foo/development
{"name":"development","label":"master","propertySources":[
  {"name":"https://github.com/scratches/config-repo/foo-development.properties","source":{"bar":"spam"}},
  {"name":"https://github.com/scratches/config-repo/foo.properties","source":{"foo":"bar"}}
]}
----

The default strategy for locating property sources is to clone a git
repository (at `spring.cloud.config.server.git.uri`) and use it to
initialize a mini `SpringApplication`. The mini-application's
`Environment` is used to enumerate property sources and publish them
via a JSON endpoint.

The HTTP service has resources in the form:

----
/{application}/{profile}[/{label}]
/{application}-{profile}.yml
/{label}/{application}-{profile}.yml
/{application}-{profile}.properties
/{label}/{application}-{profile}.properties
----

where the "application" is injected as the `spring.config.name` in the
`SpringApplication` (i.e. what is normally "application" in a regular
Spring Boot app), "profile" is an active profile (or comma-separated
list of properties), and "label" is an optional git label (defaults to
"master".)

Spring Cloud Config Server pulls configuration for remote clients
from a git repository (which must be provided):

[source,yaml]
----
spring:
  cloud:
    config:
      server:
        git:
          uri: classpath:/configs
----
